on:
  workflow_dispatch:
  push:
    branches:
      - '*'
jobs:
  check-branch-name:
    runs-on: ubuntu-latest

    steps:
      - name: Check if branch name is ok
        run: |
          branch_name=${GITHUB_HEAD_REF}
          echo "pr branch name: $branch_name"
          
          branch_regex="^(bug|feature|code-cleanup)/(OAMN|SDI|NIX|BACK)-[0-9]+_.*$"
          
          if [[ "$branch_name" != $branch_regex ]]; then
            echo "but doesn't match target branch"
            exit 1
          fi
        shell: bash
