name: Auto Merge Latest Release

on:
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write
  pull-requests: write

jobs:
  create-and-merge-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: |
          sudo apt update && sudo apt install -y gh

      - name: Authenticate with GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Get latest release branch
        id: get_latest_release
        run: |
          LATEST_BRANCH=$(git branch -r | grep 'origin/release/' | sed 's/origin\///' | sort -V | tail -n 1)
          echo "Latest release branch: $LATEST_BRANCH"
          echo "latest_branch=$LATEST_BRANCH" >> $GITHUB_ENV

      - name: Create Pull Request using GitHub CLI
        id: create_pr
        run: |
          PR_URL=$(gh pr create \
            --head "${{ env.latest_branch }}" \
            --base main \
            --title "Merge ${{ env.latest_branch }} into main" \
            --body "Automated PR to merge the latest release branch into main." \
            --label "auto-merge")
          
          echo "Pull request created: $PR_URL"
          echo "pr_number=$PR_URL" >> $GITHUB_ENV

      - name: Auto-merge PR if checks pass
        if: env.pr_number != ''
        run: |
          gh pr merge ${{ env.pr_number }} --auto --squash
