name: Auto Merge Latest Release

on:
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write
  pull-requests: write

jobs:
  create-and-merge-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Get Branches
        uses: actions/github-script@v7
        id: branches
        with:
          result-encoding: string
          script: |
            const branches = await github.rest.git.listMatchingRefs({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'heads/release/',
            });
            const regex = new RegExp("^.*(release\/[0-9]+.[0-9]+.[0-9]+.[0-9]+)$");
            let result = "";
            branches.data.forEach((branch) => {
              const match = branch.ref.match(regex);
              if (match != null) {
                result += match[1] + '\n';
              }
            });
            return result;
      - name: Get Current Release
        run: |
          LATEST_RELEASE=$(echo "${{steps.branches.outputs.result}}" | grep -o 'release/[0-9]*\.[0-9]*\.[0-9]*\.[0-9]' | sort --version-sort | tail -n1 | grep -o '[0-9]*\.[0-9]*\.[0-9]*\.[0-9]')
          echo "LATEST_RELEASE=${LATEST_RELEASE}" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const base = "main";
            const head = "${NEXT_RELEASE}";
            const { data: pull } = await github.rest.pulls.create({
              owner,
              repo,
              title: `Merge ${head} into ${base}`,
              head,
              base,
              body: "This PR was created automatically by GitHub Actions."
            });
            console.log(`Pull request created successfully: ${pull.html_url}`);
            echo "PULL_REQUEST=${pull.html_url}" >> $GITHUB_ENV

      - name: Auto-merge PR if checks pass
        if: env.pr_number != ''
        run: |
          gh pr merge ${PULL_REQUEST} --auto --no-ff
